load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "roo_locale",
    srcs = glob(
        [
            "src/**/*.h",
        ],
        exclude = ["test/**"],
    ),
    defines = [],
    includes = [
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
